name: CI Pipeline RNAseq

on:
  push:
    branch: [ "rnaseq", "dev", "feat/**" ]
  pull_request:
    branch: [ "main" ]

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: |
          cd app/
          docker build -t rnaseq .
        
      - name: Run pipeline tests
        run: |
         cd app/
         docker run --rm -v "$(pwd):/work" -w /work rnaseq bash test_rnaseq_pipeline.sh